package src.main.ui;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class Test {
    public JPanel ImportForm;
    public JPanel BottomPanel;
    public JLabel Title;
    public JPanel FileSelectorPanel;
    public JButton AddFile;
    public JButton RemoveFile;
    public JLabel FileSelectorTitle;
    public JPanel SelectorButtons;
    public JPanel ImportSettingsPanel;
    public JLabel ImportSettingsTitle;
    public JProgressBar LoadingProgressBar;
    public JButton confirmButton;
    public JButton cancelButton;
    public JPanel ConfirmationButtonPanel;
    public JRadioButton convertChunksToggle;
    public JRadioButton AntialiasingToggle;
    public JSplitPane MainSplitPane;
    public JSpinner MaxEntriesSelector;
    public JLabel MaxEntriesSelectorLabel;
    public JLabel ConvertChunksLabel;
    public JSpinner imageYOffsetSpinner;
    public JSpinner imageXOffsetSpinner;
    public JButton AddWorldImageButton;
    public JLabel AntialiasingLabel;
    public JLabel WIXOffset;
    public JLabel WIZOffset;
    public JLabel WorldImageLabel;
    public JList SelectedFileList;
    public JScrollPane SelectedFileListScrollPane;
    public JComboBox DimensionChooser;
    public JLabel DimensionChooserLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ImportForm = new JPanel();
        ImportForm.setLayout(new BorderLayout(0, 0));
        BottomPanel = new JPanel();
        BottomPanel.setLayout(new GridBagLayout());
        ImportForm.add(BottomPanel, BorderLayout.SOUTH);
        ConfirmationButtonPanel = new JPanel();
        ConfirmationButtonPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        BottomPanel.add(ConfirmationButtonPanel, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        ConfirmationButtonPanel.add(cancelButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        confirmButton = new JButton();
        confirmButton.setHideActionText(false);
        confirmButton.setOpaque(false);
        confirmButton.setRolloverEnabled(true);
        confirmButton.setSelected(true);
        confirmButton.setText("Confirm");
        ConfirmationButtonPanel.add(confirmButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        LoadingProgressBar = new JProgressBar();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        BottomPanel.add(LoadingProgressBar, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        BottomPanel.add(spacer1, gbc);
        Title = new JLabel();
        Font TitleFont = this.$$$getFont$$$(null, -1, 26, Title.getFont());
        if (TitleFont != null) Title.setFont(TitleFont);
        Title.setHorizontalAlignment(0);
        Title.setHorizontalTextPosition(0);
        Title.setText("Import Files");
        ImportForm.add(Title, BorderLayout.NORTH);
        MainSplitPane = new JSplitPane();
        MainSplitPane.setContinuousLayout(true);
        MainSplitPane.setDividerLocation(275);
        MainSplitPane.setDividerSize(9);
        MainSplitPane.setEnabled(true);
        ImportForm.add(MainSplitPane, BorderLayout.CENTER);
        FileSelectorPanel = new JPanel();
        FileSelectorPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        MainSplitPane.setRightComponent(FileSelectorPanel);
        SelectorButtons = new JPanel();
        SelectorButtons.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        FileSelectorPanel.add(SelectorButtons, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        AddFile = new JButton();
        AddFile.setText("Add");
        AddFile.setToolTipText("Add Files");
        SelectorButtons.add(AddFile, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        RemoveFile = new JButton();
        RemoveFile.setText("Remove");
        RemoveFile.setToolTipText("Remove Files");
        SelectorButtons.add(RemoveFile, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        FileSelectorTitle = new JLabel();
        Font FileSelectorTitleFont = this.$$$getFont$$$(null, -1, 16, FileSelectorTitle.getFont());
        if (FileSelectorTitleFont != null) FileSelectorTitle.setFont(FileSelectorTitleFont);
        FileSelectorTitle.setText("Select Files");
        FileSelectorPanel.add(FileSelectorTitle, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        SelectedFileListScrollPane = new JScrollPane();
        FileSelectorPanel.add(SelectedFileListScrollPane, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        SelectedFileList = new JList();
        SelectedFileListScrollPane.setViewportView(SelectedFileList);
        ImportSettingsPanel = new JPanel();
        ImportSettingsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 2, new Insets(0, 0, 0, 0), -1, -1));
        MainSplitPane.setLeftComponent(ImportSettingsPanel);
        ImportSettingsTitle = new JLabel();
        Font ImportSettingsTitleFont = this.$$$getFont$$$(null, -1, 16, ImportSettingsTitle.getFont());
        if (ImportSettingsTitleFont != null) ImportSettingsTitle.setFont(ImportSettingsTitleFont);
        ImportSettingsTitle.setText("Import Settings");
        ImportSettingsPanel.add(ImportSettingsTitle, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        convertChunksToggle = new JRadioButton();
        convertChunksToggle.setHideActionText(false);
        convertChunksToggle.setText("");
        ImportSettingsPanel.add(convertChunksToggle, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        AntialiasingToggle = new JRadioButton();
        AntialiasingToggle.setHideActionText(true);
        AntialiasingToggle.setSelected(true);
        AntialiasingToggle.setText("");
        ImportSettingsPanel.add(AntialiasingToggle, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ConvertChunksLabel = new JLabel();
        ConvertChunksLabel.setText(" Convert Chunks");
        ImportSettingsPanel.add(ConvertChunksLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        AntialiasingLabel = new JLabel();
        AntialiasingLabel.setText("Antialiasing");
        ImportSettingsPanel.add(AntialiasingLabel, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MaxEntriesSelector = new JSpinner();
        ImportSettingsPanel.add(MaxEntriesSelector, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MaxEntriesSelectorLabel = new JLabel();
        MaxEntriesSelectorLabel.setText("Max Entries");
        ImportSettingsPanel.add(MaxEntriesSelectorLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        WIXOffset = new JLabel();
        WIXOffset.setText("Image Y Offset");
        ImportSettingsPanel.add(WIXOffset, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        imageYOffsetSpinner = new JSpinner();
        ImportSettingsPanel.add(imageYOffsetSpinner, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        imageXOffsetSpinner = new JSpinner();
        ImportSettingsPanel.add(imageXOffsetSpinner, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        AddWorldImageButton = new JButton();
        AddWorldImageButton.setText("Add World Image");
        ImportSettingsPanel.add(AddWorldImageButton, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        WIZOffset = new JLabel();
        WIZOffset.setText("Image X Offset");
        ImportSettingsPanel.add(WIZOffset, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        WorldImageLabel = new JLabel();
        WorldImageLabel.setText(" World Image");
        ImportSettingsPanel.add(WorldImageLabel, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        DimensionChooserLabel = new JLabel();
        DimensionChooserLabel.setText("Dimension");
        ImportSettingsPanel.add(DimensionChooserLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        DimensionChooser = new JComboBox();
        ImportSettingsPanel.add(DimensionChooser, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MaxEntriesSelectorLabel.setLabelFor(MaxEntriesSelector);
        WIXOffset.setLabelFor(imageYOffsetSpinner);
        WIZOffset.setLabelFor(imageXOffsetSpinner);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ImportForm;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
